version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/build
    overwrite: yes
file_exists_behavior: OVERWRITE
    
hooks:
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 60
      runas: ubuntu
