version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/build
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/deploy-before.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/server_start.sh
      runas: ec2-user
