version: 0.0
os: linux

files:
  - source: /docker-compose.yml
    destination: /home/ubuntu/
    overwrite: yes
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 300
      runas: root
