version: 0.0
os: linux

files:
  - source: /docker-compose.yml
    destination: /home/ubuntu/
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
