version: "3.7"

services:
  blue:
    image : ${REPO_URL}
    ports:
      - 8080:8080
      
  green:
    image : ${REPO_URL}
    ports:
      - 8090:8080
      
  logging:
    driver: awslogs
    options:
      awslogs-group: "sms-logs"
      awslogs-region: "ap-northeast-2"
      awslogs-stream: "web/error"
