version: "3.7"

services:
  web-server:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
  blue:
    image : ${REPO_URL}
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./:/home/ubuntu
      - /etc/localtime:/etc/localtime
      
  green:
    image: ${REPO_URL}
    container_name: ${YOUR_APPLICATION_CONTAINER_NAME}
    restart: always
    expose:
      - "8080"
    volumes:
      - ./:/home/ubuntu
      - /etc/localtime:/etc/localtime
