version: "3.7"

services:
  blue:
    image : ${REPO_URL}
    ports:
      - 8080:8080
    networks:
      - backend

  green:
    image : ${REPO_URL}
    ports:
      - 8090:8080
    networks:
      - backend

  redis:
    image : redis:alpine
    ports:
      - 6379:6379

  nginx:
    image : ${NGINX_URL}
    ports:
      - 80:80
    networks:
      - backend
    command: service nginx start


networks:
  backend:
    driver: bridge
