version: "3.7"

services:
  blue:
    image : ${REPO_URL}
    ports:
      - 8080:8080
      
  green:
    image : ${REPO_URL}
    ports:
      - 8090:8080
      
  myservice:
    logging:
    driver: awslogs
    options:
      awslogs-region: ap-northeast-2
