version: "3.7"

services:
  blue:
    image : ${REPO_URL}
    container_name: ${YOUR_APPLICATION_CONTAINER_NAME}-blue
    restart: always
    ports:
      - '8080:8000'
      
  green:
    image: ${REPO_URL}
    container_name: ${YOUR_APPLICATION_CONTAINER_NAME}-green
    restart: always
    ports:
      - '8081:8000'
