version: "3.7"

services:
  blue:
    image : ${REPO_URL}
    restart: always
    ports:
      - 8080:8080
      
  green:
    image : ${REPO_URL}
    restart: always
    ports:
      - 8080:8080 
      
      
