version: "3.7"

services:
  main:
    image : ${REPO_URL}/${ECR_REPOSITORY}:${IMAGE_TAG}
    ports:
      - 8080:8080
    networks:
      - backend

  redis:
    image : redis:alpine
    ports:
      - 6379:6379
    networks:
      - backend


networks:
  backend:
    driver: bridge
