object DependencyVersions {
    const val JACKSON_VERSION = "2.10.3"
    const val JWT_VERSION = "0.9.1"
    const val REDIS_VERSION = "2.7.2"
    const val MYSQL = "8.0.28"
    const val MOCKITO_VERSION = "4.0.0"
    const val AWS_VERSION = "2.2.6.RELEASE"
    const val SERVLET_VERSION = "4.0.1"
    const val GAUTH_VERSION = "2.0.0"
    const val SPRING_TRANSACTION = "5.3.22"
    const val QUERYDSL = "5.0.0"
    const val MARIA_VERSION = "2.1.2"
    const val KOTEST_VERSION = "5.4.2"
    const val KOTEST_EXTENSION_VERSION = "1.1.2"
}