name: Deploy to cloudtype
on:
  push:
    branches:
      - feature/255-develop-branch-cd-add
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SMS-Backend-CD Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: ℹ️ SMS-Backend-CD 시작! ℹ️
          webhook: ${{ secrets.SMS_DISCORD_WEBHOOK }}
          color: 00FF00

      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: seungwon/movie
          stage: main
          yaml: >
            name: sms-backend

            app: java@11

            options:
              ports: 8080
              includes: sms-infrastructure
              env:
                - name: AWS_ACCESS_KEY
                  var: AWS_ACCESS_KEY
                - name: AWS_REGION_STATIC
                  var: var: AWS_ACCESS_KEY
                - name: AWS_SECRET_KEY
                  var: AWS_SECRET_KEY
                - name: DB_DRIVER
                  value: org.mariadb.jdbc.Driver
                - name: DB_PASSWORD
                  var: DB_PASSWORD
                - name: DB_URL
                  var: DB_URL
                - name: DB_USERNAME
                  var: DB_USERNAME
                - name: GAUTH_CLIENT_ID
                  var: GAUTH_CLIENT_ID
                - name: GAUTH_CLIENT_SECRET
                  var: GAUTH_CLIENT_SECRET
                - name: GAUTH_REDIRECT_URI
                  var: GAUTH_REDIRECT_URI
                - name: JWT_ACCESS_SECRET
                  var: JWT_ACCESS_SECRET
                - name: JWT_REFRESH_SECRET
                  var: JWT_REFRESH_SECRET
                - name: REDIS_HOST
                  var: REDIS_HOST
                - name: REDIS_PORT
                  var: REDIS_PORT
                - name: S3_BUCKET
                  var: S3_BUCKET
                - name: S3_LOG_BUCKET
                  var: S3_LOG_BUCKET
                - name: SECURITY_SECRET_KEY
                  var: SECURITY_SECRET_KEY
              start: java -jar sms-infrastructure/build/libs/sms-infrastructure-0.0.1-SNAPSHOT.jar
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: kotlin

      - name: SMS-Backend-CD Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: ✅ SMS-Backend-CD 성공! ✅
          webhook: ${{ secrets.SMS_DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          image: ${{ secrets.CD_SUCCESS_IMAGE }}
          description: 영역전개 CD 성공
          color: 00FF00
          username: SMS CD 봇

      - name: SMS-Backend-CD Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: ❗️ SMS-Backend-CD 실패! ❗️
          webhook: ${{ secrets.SMS_DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          image: ${{ secrets.CD_FAIL_IMAGE }}
          description: 무례하긴, 실패다.
          color: FF0000
          username: SMS CD 봇