name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "*" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Clean Gradle cache
        run: rm -rf $HOME/.gradle/caches

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create application.yml
        run: |
          mkdir ./sms-infrastructure/src/main/resources
          touch ./sms-infrastructure/src/main/resources/application.yml
          echo "${{ secrets.SMS_BACKEND_ENV }}" > ./sms-infrastructure/src/main/resources/application.yml
        shell: bash

      - name: Run build with Gradle wrapper
        run: ./gradlew clean build

      - name: SMS Backend CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: ✅ SMS-Backend-CI 성공! ✅
          webhook: ${{ secrets.SMS_DISCORD_WEBHOOK }}
          color: 00FF00

      - name: SMS Backend CI Discord Notification
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: ❗️ SMS-Backend-CI 실패! ❗️
          webhook: ${{ secrets.SMS_DISCORD_WEBHOOK }}
          color: FF0000
